name: "CI"

on:
  push:
    branches:
      - "master"
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: "3"
  HUSKY: "0"

concurrency: "${{ github.workflow }}-${{ github.ref }}"

jobs:
  format:
    name: "Check Format"
    runs-on: "ubuntu-22.04-arm"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v5"

      - name: "Install pnpm"
        uses: "pnpm/action-setup@v4"

      - name: "Setup Node.js"
        uses: "actions/setup-node@v5"
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - name: "Install Dependencies"
        run: |
          pnpm install --frozen-lockfile

      - name: "Check Format"
        run: |
          pnpm format:check

  build:
    name: "Build Library"
    runs-on: "ubuntu-22.04-arm"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v5"

      - name: "Install pnpm"
        uses: "pnpm/action-setup@v4"

      - name: "Setup Node.js"
        uses: "actions/setup-node@v5"
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - name: "Install Dependencies"
        run: |
          pnpm install --frozen-lockfile

      - name: "Build Library"
        run: |
          pnpm build

  knip:
    name: "Check Dead Code"
    runs-on: "ubuntu-22.04-arm"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v5"

      - name: "Install pnpm"
        uses: "pnpm/action-setup@v4"

      - name: "Setup Node.js"
        uses: "actions/setup-node@v5"
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - name: "Install Dependencies"
        run: |
          pnpm install --frozen-lockfile

      - name: "Check Dead Code"
        run: |
          pnpm knip

      - name: "Check Dead Code (Production)"
        run: |
          pnpm knip:prod

  test:
    name: "Cypress Tests"
    runs-on: "ubuntu-22.04-arm"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v5"

      - name: "Install pnpm"
        uses: "pnpm/action-setup@v4"

      - name: "Setup Node.js"
        uses: "actions/setup-node@v5"
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - name: "Get pnpm store path"
        id: pnpm-cache
        run: echo "PNPM_STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: "Cache pnpm modules and Cypress binary"
        uses: "actions/cache@v4"
        with:
          path: |
            ${{ steps.pnpm-cache.outputs.PNPM_STORE_PATH }}
            ~/.cache/Cypress
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: "Install Dependencies"
        run: |
          pnpm install --frozen-lockfile

      - name: "Cypress Tests"
        run: |
          pnpm cypress:run
