name: "CI"

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: "3"

concurrency: "${{ github.workflow }}-${{ github.ref }}"

jobs:
  format:
    name: "Check Format"
    runs-on: "ubuntu-22.04-arm"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v5"

      - name: "Setup Nix Environment"
        uses: "./.github/actions/setup-nix"

      - name: "Install Dependencies"
        run: |
          nix develop .#ci --command pnpm install --frozen-lockfile

      - name: "Check Format"
        run: |
          nix develop .#ci --command pnpm format:check

  build:
    name: "Build Library"
    runs-on: "ubuntu-22.04-arm"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v5"

      - name: "Setup Nix Environment"
        uses: "./.github/actions/setup-nix"

      - name: "Install Dependencies"
        run: |
          nix develop .#ci --command pnpm install --frozen-lockfile

      - name: "Build Library"
        run: |
          nix develop .#ci --command pnpm build

  knip:
    name: "Run Knip"
    runs-on: "ubuntu-22.04-arm"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v5"

      - name: "Setup Nix Environment"
        uses: "./.github/actions/setup-nix"

      - name: "Install Dependencies"
        run: |
          nix develop .#ci --command pnpm install --frozen-lockfile

      - name: "Test Formatting"
        run: |
          nix develop .#ci --command pnpm knip

  test:
    name: "Cypress Tests"
    runs-on: "ubuntu-22.04-arm"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v5"

      - name: "Setup Nix Environment"
        uses: "./.github/actions/setup-nix"

      - name: "Install Dependencies"
        run: |
          nix develop .#ci --command pnpm install --frozen-lockfile

      - name: "Cypress Tests"
        run: |
          nix develop .#ci --command pnpm cypress:run
